"""add attachment columns to invoices

Revision ID: c3684dd713d8
Revises: 06ffcb000180
Create Date: 2026-07-31 01:02:39.244093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3684dd713d8'
down_revision: Union[str, Sequence[str], None] = '06ffcb000180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('attachment_name', sa.String(length=255), nullable=True))
    op.add_column('invoices', sa.Column('attachment_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'attachment_path')
    op.drop_column('invoices', 'attachment_name')
    # ### end Alembic commands ###
