"""add recurrence columns to invoices

Revision ID: d0bc35a9a3a9
Revises: c3684dd713d8
Create Date: 2026-07-31 02:58:55.583220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0bc35a9a3a9'
down_revision: Union[str, Sequence[str], None] = 'c3684dd713d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('recurrence', sa.String(length=20), nullable=True))
    op.add_column('invoices', sa.Column('recurrence_parent_id', sa.Integer(), nullable=True))
    # Kısıta İSİM veriyoruz: Alembic None bırakmıştı, o zaman downgrade() onu bulup silemezdi.
    op.create_foreign_key(
        'fk_invoices_recurrence_parent', 'invoices', 'invoices',
        ['recurrence_parent_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_invoices_recurrence_parent', 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'recurrence_parent_id')
    op.drop_column('invoices', 'recurrence')
    # ### end Alembic commands ###
